In [1]:
import pandas as pd

In [34]:
df = pd.read_csv("q1_player_shooting_raw.csv", header=1)
df.head()

,Rk,Player,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches,-9999
0,1,Brenden Aaronson,MF,us USA,25,2000,0.8,0,3,1,33.3,3.55,1.18,0.0,0.0,0,0,Matches,5bc43860
1,2,Thelo Aasgaard,MF,no Norway,24,2002,1.0,1,2,1,50.0,2.00,1.00,0.5,1.0,0,0,Matches,c88a28b9
2,3,Hamza Abdelkarim,FW,eg Egypt,18,2008,0.7,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches,057d8f12
3,4,Hossam Abdelmaguid,DF,eg Egypt,25,2001,0.7,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches,accbfc94
4,5,Mohamed Abdelmonem,DF,eg Egypt,27,1999,0.2,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches,bff15d74

In [12]:
df = df.drop(columns=["Matches", "-9999"])
df.head()

,Rk,Player,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt
0,1,Brenden Aaronson,MF,us USA,25,2000,0.8,0,3,1,33.3,3.55,1.18,0.0,0.0,0,0
1,2,Thelo Aasgaard,MF,no Norway,24,2002,1.0,1,2,1,50.0,2.00,1.00,0.5,1.0,0,0
2,3,Hamza Abdelkarim,FW,eg Egypt,18,2008,0.7,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0
3,4,Hossam Abdelmaguid,DF,eg Egypt,25,2001,0.7,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0
4,5,Mohamed Abdelmonem,DF,eg Egypt,27,1999,0.2,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0

In [15]:
forwards = df[df["Pos"].str.contains("FW", na=False)].copy()
forwards.head()

,Rk,Player,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt
2,3,Hamza Abdelkarim,FW,eg Egypt,18,2008,0.7,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0
8,9,Yusuf Abdurisag,FW,qa Qatar,26,1999,1.1,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0
15,16,Elias Achouri,FWMF,tn Tunisia,27,1999,0.5,0,3,1,33.3,6.28,2.09,0.0,0.0,0,0
16,17,Ché Adams,FW,sct Scotland,29,1996,1.6,0,1,1,100.0,0.62,0.62,0.0,0.0,0,0
21,22,Simon Adingra,FWMF,ci Côte d'Ivoire,24,2002,0.2,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0

In [16]:
forwards = forwards[["Player", "Squad", "90s", "SoT", "SoT/90"]]
forwards.head()

              Player             Squad  90s  SoT  SoT/90
2   Hamza Abdelkarim          eg Egypt  0.7    0    0.00
8    Yusuf Abdurisag          qa Qatar  1.1    0    0.00
15     Elias Achouri        tn Tunisia  0.5    1    2.09
16         Ché Adams      sct Scotland  1.6    1    0.62
21     Simon Adingra  ci Côte d'Ivoire  0.2    0    0.00

In [17]:
forwards["Squad"] = forwards["Squad"].str.split(" ", n=1).str[1]
forwards.head()

              Player          Squad  90s  SoT  SoT/90
2   Hamza Abdelkarim          Egypt  0.7    0    0.00
8    Yusuf Abdurisag          Qatar  1.1    0    0.00
15     Elias Achouri        Tunisia  0.5    1    2.09
16         Ché Adams       Scotland  1.6    1    0.62
21     Simon Adingra  Côte d'Ivoire  0.2    0    0.00

In [20]:
knockout_teams = [
    "South Africa", "Canada", "Brazil", "Japan", "Germany", "Paraguay",
    "Netherlands", "Morocco", "Côte d'Ivoire", "Norway", "France", "Sweden",
    "Mexico", "Ecuador", "England", "Congo DR", "Belgium", "Senegal",
    "USA", "Bosnia–Herz", "Spain", "Austria", "Portugal", "Croatia",
    "Switzerland", "Algeria", "Australia", "Egypt", "Argentina",
    "Cabo Verde", "Colombia", "Ghana"
]

print(len(knockout_teams))

32

In [22]:
forwards["Stage"] = forwards["Squad"].apply(
    lambda team: "Knockout" if team in knockout_teams else "Group Stage Only"
)

forwards.head()

              Player          Squad  90s  SoT  SoT/90             Stage
2   Hamza Abdelkarim          Egypt  0.7    0    0.00          Knockout
8    Yusuf Abdurisag          Qatar  1.1    0    0.00  Group Stage Only
15     Elias Achouri        Tunisia  0.5    1    2.09  Group Stage Only
16         Ché Adams       Scotland  1.6    1    0.62  Group Stage Only
21     Simon Adingra  Côte d'Ivoire  0.2    0    0.00          Knockout

In [23]:
forwards = forwards[forwards["90s"] > 0]
print(f"Total forwards after removing non-players: {len(forwards)}")
forwards.head()

Total forwards after removing non-players: 262

              Player          Squad  90s  SoT  SoT/90             Stage
2   Hamza Abdelkarim          Egypt  0.7    0    0.00          Knockout
8    Yusuf Abdurisag          Qatar  1.1    0    0.00  Group Stage Only
15     Elias Achouri        Tunisia  0.5    1    2.09  Group Stage Only
16         Ché Adams       Scotland  1.6    1    0.62  Group Stage Only
21     Simon Adingra  Côte d'Ivoire  0.2    0    0.00          Knockout

In [24]:
forwards["Stage"].value_counts()

Stage
Knockout            185
Group Stage Only     77
Name: count, dtype: int64

In [25]:
knockout_sample = forwards[forwards["Stage"] == "Knockout"].sample(n=30, random_state=42)
group_sample = forwards[forwards["Stage"] == "Group Stage Only"].sample(n=30, random_state=42)

sample = pd.concat([knockout_sample, group_sample])

print(sample["Stage"].value_counts())
sample.head()

Stage
Knockout            30
Group Stage Only    30
Name: count, dtype: int64

                    Player        Squad  90s  SoT  SoT/90     Stage
112           Samed Baždar  Bosnia–Herz  0.3    0    0.00  Knockout
244      Ermedin Demirović  Bosnia–Herz  3.9    4    1.02  Knockout
903  Crysencio Summerville  Netherlands  2.8    2    0.71  Knockout
647             Petar Musa      Croatia  1.2    1    0.82  Knockout
865          Kento Shiogai        Japan  0.1    0    0.00  Knockout

In [26]:
sample["SoT/90"].describe()

count    60.000000
mean      0.652167
std       0.879440
min       0.000000
25%       0.000000
50%       0.280000
75%       1.132500
max       4.500000
Name: SoT/90, dtype: float64

In [29]:
sample.groupby("Stage")["SoT/90"].describe()

                  count      mean       std  min  25%    50%    75%   max
Stage
Group Stage Only   30.0  0.714000  1.070735  0.0  0.0  0.000  1.155  4.50
Knockout           30.0  0.590333  0.647390  0.0  0.0  0.315  1.110  1.88

In [28]:
from scipy import stats

mean = sample["SoT/90"].mean()
std = sample["SoT/90"].std()
n = len(sample)

confidence_level = 0.95
degrees_freedom = n - 1

confidence_interval = stats.t.interval(
    confidence_level,
    degrees_freedom,
    loc=mean,
    scale=std / (n ** 0.5)
)

print(f"Sample mean: {mean:.3f}")
print(f"95% Confidence Interval: {confidence_interval}")

Sample mean: 0.652
95% Confidence Interval: (np.float64(0.42498334849296715), np.float64(0.8793499848403662))

In [31]:
from scipy import stats

knockout_values = sample[sample["Stage"] == "Knockout"]["SoT/90"]
group_values = sample[sample["Stage"] == "Group Stage Only"]["SoT/90"]

t_stat, p_value = stats.ttest_ind(knockout_values, group_values)

print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

t-statistic: -0.5413
p-value: 0.5903